DROP TABLE IF EXISTS tenancy_contracts;
DROP TABLE IF EXISTS purchase_contracts;
DROP TABLE IF EXISTS contracts CASCADE;
DROP TABLE IF EXISTS houses;
DROP TABLE IF EXISTS apartments;
DROP TABLE IF EXISTS estates CASCADE;
DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS estate_agents CASCADE;
DROP TABLE IF EXISTS sells;
DROP TABLE IF EXISTS rents;


